#!/bin/bash
# Quick Start: Running Chatbot Tests

echo "════════════════════════════════════════════════════════════════"
echo "🤖 FITFAAT CHATBOT TEST QUICK START"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📍 Two test scripts available:"
echo ""
echo "1️⃣  BASIC TEST (Quick & Simple)"
echo "   File: test-chatbot-basic.js"
echo "   Time: ~10-30 seconds"
echo "   Shows: Question, Response, Source, Time"
echo "   Run: node test-chatbot-basic.js"
echo ""

echo "2️⃣  INTERACTIVE TEST (Comprehensive & Detailed)"
echo "   File: test-chatbot-interactive.js"
echo "   Time: ~30-60 seconds"
echo "   Shows: Full details + Analytics + Timing + History"
echo "   Run: node test-chatbot-interactive.js"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🚀 RUN TESTS"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Option 1: Run basic test (fastest)"
echo "  cd /Users/mc/Desktop/FitFaat/backend"
echo "  node test-chatbot-basic.js"
echo ""

echo "Option 2: Run comprehensive test (most info)"
echo "  cd /Users/mc/Desktop/FitFaat/backend"
echo "  node test-chatbot-interactive.js"
echo ""

echo "Option 3: Run both tests"
echo "  cd /Users/mc/Desktop/FitFaat/backend"
echo "  node test-chatbot-basic.js && echo '' && node test-chatbot-interactive.js"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "📋 TEST QUESTIONS"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Dataset Queries (Should find data):"
echo "  1. 'I am gonna eat biryani, how many calories will I get?'"
echo "  2. 'How much protein is in chicken tandoori?'"
echo "  3. 'How many carbs are in a bowl of rice?'"
echo "  4. 'What is the hydration level of orange juice?'"
echo ""

echo "Non-Dataset Queries (Should show guidance):"
echo "  1. 'How can I lose weight?'"
echo "  2. 'How can I gain weight?'"
echo "  3. 'Can you suggest post-workout nutrition?'"
echo "  4. 'What can I eat to increase my energy levels?'"
echo ""

echo "Health Queries:"
echo "  1. 'Tell me about vitamins in spinach'"
echo "  2. 'I want to improve my sleep quality, any tips?'"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "📊 SESSION ID"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "All tests use: test-session-001"
echo "This maintains conversation context across all questions"
echo "After test, use getSessionHistory('test-session-001') to view"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "✨ WHAT TO EXPECT"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Dataset Queries:"
echo "   Response: Nutritional info with emojis (🍽️ 🔥 💪 🌾 🧈)"
echo "   Source: dataset"
echo "   Time: <100ms"
echo ""

echo "✅ Guidance Messages:"
echo "   Response: 'I can provide calories, protein, fat, carbs...'"
echo "   Source: system"
echo "   Time: <10ms"
echo ""

echo "✅ Health Queries:"
echo "   Response: Health information with tips"
echo "   Source: health-dataset"
echo "   Time: <500ms"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "For detailed documentation, see:"
echo "  • TEST_SCRIPTS_GUIDE.md - Complete guide"
echo "  • DATASET_FILTER_SUMMARY.md - Dataset filter info"
echo "  • ENHANCED_CHATBOT_GUIDE.md - Full chatbot docs"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "Ready to test! Pick an option above and run it."
echo "════════════════════════════════════════════════════════════════"
echo ""
