import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export const dataScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  headingandlogo: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  logoImage: {
    height: hp(8),
    width: hp(8),
  },
  subContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  mainHeading: {
    textAlign: "center",
    marginTop: hp(1.5),
    fontSize: hp(3.6),
    fontFamily: "LoraRegular",
  },
  gettingStarted: {
    textAlign: "left",
    marginTop: hp(1.5),
    fontSize: hp(2),
    fontWeight: 700,
    paddingLeft: hp(6),
  },
  mainBox: {
    height: hp(80),
    width: wp(80),
    borderWidth: hp(0.1),
    borderColor: "black",
    display: "flex",
    alignSelf: "center",
    marginTop: hp(0.5),
    borderRadius: hp(2),
  },
  personalizedText: {
    textAlign: "center",
    marginTop: hp(1),
    fontSize: hp(2),
    fontFamily: "LoraRegular",
  },
  subHeading: {
    marginTop: hp(0.5),
    fontSize: hp(2),
    paddingLeft: hp(2),
    fontFamily: "LoraRegular",
  },
  subsubHeading: {
    marginTop: hp(0.5),
    fontSize: hp(2),
    paddingLeft: hp(0.8),
    fontFamily: "LoraRegular",
  },
  genderHeading: {
    marginTop: hp(0.5),
    fontSize: hp(2),
    paddingLeft: hp(2),
    textAlign: "left",
    fontFamily: "LoraRegular",
  },
  mainTextInput: {
    height: hp(4.8),
    width: wp(70),
    backgroundColor: "white",
    display: "flex",
    alignSelf: "center",
    justifyContent: "center",
    borderWidth: hp(0.1),
    borderColor: "#ccc",
    borderRadius: hp(1),
    marginTop: hp(0.3),
    fontSize: hp(1.8),
    textAlign: "left",
  },
  miniTextInput: {
    height: hp(5),
    width: wp(35),
    backgroundColor: "white",
    display: "flex",
    alignSelf: "center",
    borderWidth: hp(0.1),
    borderColor: "#ccc",
    borderRadius: hp(1),
    marginTop: hp(0.2),
    textAlign: "center",
    fontSize: hp(1.8),
  },
  genderSelection: {
    height: hp(6),
    width: hp(10),
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: hp(0.1),
    borderColor: "#ccc",
    borderRadius: hp(1),
  },
  dob: {
    flexDirection: "row",
    display: "flex",
    alignSelf: "center",
    alignItems: "center",
    borderWidth: hp(0.1),
    borderColor: "#ccc",
    borderRadius: hp(1),
    height: hp(5.5),
    width: wp(70),
  },
  dobInput: {
    flex: 1,
    height: hp(6),
    textAlign: "center",
    fontSize: hp(1.8),
  },
  dobText: {
    fontSize: hp(2),
    marginBottom: hp(0.6),
    color: "#000",
  },
  mappingCol: {
    flexDirection: "column",
    alignSelf: "center",
    width: wp(65),
    marginTop: hp(0.2),
  },
  mapping: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: hp(0.1),
    borderColor: "#ccc",
    borderRadius: hp(1),
    padding: hp(1),
    marginBottom: hp(1),
    backgroundColor: "#fff",
  },
  mappingHeading: {
    fontSize: hp(1.8),
    fontFamily: "LoraItalic",
    color: "#000",
  },
  mappingHeadingName: {
    fontSize: hp(1.4),
    color: "#555",
    marginTop: 2,
    flexShrink: 1,
    fontFamily: "LoraRegular",
  },
  generateButton: {
    height: hp(5),
    width: wp(70),
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "blue",
    marginTop: hp(1),
    borderRadius: hp(1),
  },
});
