export type Day = {
  _id?: string, // MongoDB daily log ID
  dayNo: number,
  date: string,
  achievedCalories : number,
  achieviedHydration: number,
  baseTargetCalories?: number,
  baseTargetHydration?: number,
  targetCalories: number,
  targetHydration: number,
  targetCaloriesMin?: number,
  targetCaloriesMax?: number,
  targetHydrationMin?: number,
  targetHydrationMax?: number,
  calibratedTargetCalories?: number,
  adaptiveCaloriesAdjustment?: number,
  adaptiveHydrationAdjustment?: number,
  idealTargetCalories?: number,
  idealTargetHydration?: number,
  weightTrendCaloriesAdjustment?: number,
  weightTrendExpectedKgPerWeek?: number,
  weightTrendObservedKgPerWeek?: number,
  weightTrendConfidence?: number,
  weightTrendStatus?: "collecting" | "onTrack" | "adjusting",
  weightTrendMessage?: string,
  weightTrendGoalDirection?: "weightLoss" | "muscleGain" | "weightGain" | "maintenance",
  behaviorCaloriesAdjustment?: number,
  behaviorHydrationAdjustment?: number,
  calorieGap?: number,
  hydrationGap?: number,
  calorieGoalDirection?: "missed" | "exceeded" | "onTarget" | "unknown",
  nutritionGapSeverity?: "none" | "low" | "medium" | "high" | "critical",
  hydrationRiskScore?: number,
  recoveryNeedScore?: number,
  goalRiskScore?: number,
  nudgePriority?: "silent" | "low" | "medium" | "high",
  nudgeReason?: string,
  exerciseCaloriesBurned?: number,
  exerciseDurationSeconds?: number,
  walkingSteps?: number,
  walkingStepGoal?: number,
  walkingHasStepSignal?: boolean,
  walkingHasExplicitStepGoal?: boolean,
  walkingHasPedometerPermission?: boolean,
  walkingPedometerPermissionStatus?: string | null,
  walkingCaloriesBurned?: number,
  targetWalkingCaloriesBurned?: number,
  targetWalkingCalories?: number,
  walkingCaloriesTarget?: number,
  stepCaloriesTarget?: number,
  targetStepCalories?: number,
  targetExerciseCaloriesBurned?: number,
  targetExerciseCalories?: number,
  targetBurnedCalories?: number,
  exerciseCaloriesTarget?: number,
  burnedCaloriesTarget?: number,
  workoutCaloriesTarget?: number,
  dailyBurnedCaloriesTarget?: number,
  exerciseEntries?: {
    exerciseName: string,
    caloriesBurned: number,
    durationSeconds: number,
    completedAt: string,
  }[],
  remarks: string | null, 
  duration: number, // in seconds, sync with API //determines when to refresh data 
  status?: "locked" | "active" | "finished" // using to detemine if finished or active or locked
}

export type jsonResponse = {
  day01: Day,
  day02: Day,
  day03: Day,
  day04: Day,
  day05: Day,
  day06: Day,
  day07: Day
}
